[project]
name = "mcp-voleyball"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasette>=0.65.1",
    "mcp[cli]>=1.20.0",
    "requests>=2.31.0",
]
